# Generated by Django 5.0.6 on 2024-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfileupload",
            name="creator_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
