# Generated by Django 5.0.6 on 2024-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0003_alter_myfileupload_my_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfileupload",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
