# Generated by Django 5.0.6 on 2024-06-29 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0005_dataset_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfileupload",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
