# Generated by Django 5.0.6 on 2024-06-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0007_myfileupload_selected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myfileupload",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="myfileupload",
            name="selected",
        ),
    ]
