# Generated by Django 5.0.6 on 2024-07-02 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0008_remove_myfileupload_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfileupload",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
