# Generated by Django 5.0.6 on 2024-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UploadFiles", "0010_myfileupload_project_id_alter_dataset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfileupload",
            name="project_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
